name: Build LibrimeKit

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    permissions:
      contents: write  # This is important for creating releases
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to v4
        with:
          submodules: recursive

      - name: Restore Cache Boost
        id: cache-boost-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/frameworks
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/dest
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/scripts
          key: ${{ runner.os }}-boost

      - name: Build Boost
        if: steps.cache-boost-restore.outputs.cache-hit != 'true'
        run: |
          make boost-build

      - name: Copy Boost
        if: steps.cache-boost-restore.outputs.cache-hit == 'true'
        run: |
          make boost-copy

      - name: Save Cache Boost
        id: cache-boost-save
        uses: actions/cache/save@v3
        with:
          path: |
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/frameworks
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/dest
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/scripts
          key: ${{ runner.os }}-boost

      - name: Build Librime
        run: |
          make librime-build

      - name: Make Archive
        run: |
          tar -acf Frameworks.tgz Frameworks

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: librimekit-frameworks
          path: Frameworks.tgz

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Frameworks.tgz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
