name: Build LibrimeKit

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Ensure Cache Directory Exists
        run: mkdir -p /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/frameworks

      - name: Debug Cache Directory
        run: ls -lah /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx || echo "Boost directory does not exist"

      - name: Restore Cache Boost
        id: cache-boost-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/frameworks
          key: ${{ runner.os }}-boost

      - name: Build Boost
        if: steps.cache-boost-restore.outputs.cache-hit != 'true'
        run: make boost-build

      - name: Copy Boost
        if: steps.cache-boost-restore.outputs.cache-hit == 'true'
        run: make boost-copy

      - name: Save Cache Boost
        id: cache-boost-save
        uses: actions/cache/save@v3
        with:
          path: /Users/runner/work/LibrimeKit/LibrimeKit/boost-iosx/frameworks
          key: ${{ runner.os }}-boost

      - name: Build Librime
        run: make librime-build

      - name: Verify Build Output
        run: ls -lah

      - name: Make Archive
        run: tar -acf Frameworks.tgz Frameworks

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: librimekit-frameworks
          path: Frameworks.tgz

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Frameworks.tgz
          asset_name: Frameworks.tgz
          asset_content_type: application/gzip
